server:
  port: 12000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/itdds/springcloud-config.git
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka